title: tattooist hong kong
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.4103943
  lightness: 0.5
  brandColors:
    - '#3a3a3c'
    - '#dedddb'
    - '#565658'
    - '#888888'
    - '#ababaa'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: lesshunter
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.23715
layout_spectrum: 1
