name: lesshunter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1736534801311791
title: tattooist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a3a3c'
    - '#dedddb'
    - '#565658'
    - '#888888'
    - '#ababaa'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
